#!/usr/bin/python
DIRECTION_UP = 0
DIRECTION_DOWN = 1
DIRECTION_LEFT = 2
DIRECTION_RIGHT = 3

# To be initialized at runtime
SCREEN_DIMENSIONS = None
LENGTH = None
HEIGHT = None

X_CENTER = None
Y_CENTER = None

BOARD_EDGES = None
BORDERS = None
CORNERS = None

DISPLAY_SNAKE = None
DISPLAY_FOOD = None
DISPLAY_EMPTY = None

PLAYER_KEYS = []
QUIT_KEY = None

ITERATION_DELAY = None
